class_name VoiceLines
extends RefCounted
## Generated by D:/Claude/tts/make_voice_index.py - do not edit by hand.
## Every spoken line: [English text, clip file in assets/voice, speaker].
const LINES := [
	["The Vale split open on the Night of Breaking, and it has not closed since. Rifts bleed monsters into the farmland. The largest breach belongs to Vaelith, and the villages say she wears the green of an Accord ranger. Seal it, and find out why.", "CAMPAIGN_0_.intro.ogg", "narrator"],   # CAMPAIGN[0].intro
	["Vaelith falls back through the Breach, and it seals behind her. Under her cloak was an Accord badge with the oath scratched out: she was one of them, and she left her post. Whatever the old guilds did that night, someone has been undoing it. Greater Rifts are open to your guild.", "CAMPAIGN_0_.outro.ogg", "narrator"],   # CAMPAIGN[0].outro
	["South of the Vale the marshes have risen, and Nyxara's spire rises with them. Before it drowned, the Spire was the Accord's archive: every contract, every name, every oath. Nyxara keeps it now, with a light burning at the bottom. The villages will only trust a guild that has proven itself.", "CAMPAIGN_1_.intro.ogg", "narrator"],   # CAMPAIGN[1].intro
	["The Spire crumbles into the black water, and Nyxara with it. One book survived the archive, in the Grandmaster's hand, and it says the guilds did not fall that night. They made a bargain. Beneath the Spire, something vast stirs: a rift with no bottom, lit by pillars of light. The Endless Rift is open to your guild.", "CAMPAIGN_1_.outro.ogg", "narrator"],   # CAMPAIGN[1].outro
	["Every rift you've sealed led here. At the heart of the rift network sits Sythrane in a crown of ash, guarded by Korrath and Drevok, once her wardens. The Grandmaster's book names her plainly: Sythrane, Grandmaster of the Accord. She made the bargain. Every breach in the world is one of her guilds letting go, and every one feeds her.", "CAMPAIGN_2_.intro.ogg", "narrator"],   # CAMPAIGN[2].intro
	["The Ashen Crown shatters. Sythrane's last words are not a threat but a warning: someone has to hold the Hollow shut, and she was tired. One by one the rifts fall quiet, and for the first time in years the sky is only sky. In the Endless Rift the pillars of light are still holding. Your guild's name will be told for generations.", "CAMPAIGN_2_.outro.ogg", "narrator"],   # CAMPAIGN[2].outro
	["With Sythrane gone, the Hollow has no one to bargain with, so it is bargaining with the posts directly. One by one the pillars in the Endless Rift are flickering. The Accord Hall lies below them, and in it the Terms that started all of this, wearing the Grandmaster's face. Every post that has gone dark makes them stronger. Someone will have to read them out loud.", "CAMPAIGN_3_.intro.ogg", "narrator"],   # CAMPAIGN[3].intro
	["The Terms come apart into forty-one lines of old ink, and the Hall goes quiet. The posts are listening. The bargain needs a last signature, or a fire. Your guild has to choose.", "CAMPAIGN_3_.outro.ogg", "narrator"],   # CAMPAIGN[3].outro
	["Under the Accord Hall the Endless Rift has a floor now, and the floor is glass. Below it is a shore the sky comes down to meet: sea-glass sand, tides that fall upward, and the villages of the Hollow's people, who were never only monsters. Their sky is falling. The Tidewarden has kept this shore since the Terms were signed. Find out what the Grandmaster promised them.", "CAMPAIGN_4_.intro.ogg", "narrator"],   # CAMPAIGN[4].intro
	["The Tidewarden kneels in the glass and lays down a key shaped like a wave. The bargain, it says, was simple: the Vale would hold its doors shut, and the Hollow would not knock. It has kept its side for twenty years while its sky came down. Beyond the shore, the last city of the Hollow hangs upside down from the falling sky.", "CAMPAIGN_4_.outro.ogg", "narrator"],   # CAMPAIGN[4].outro
	["The Inverted City hangs over nothing by cords as thick as towers, and they are fraying one by one. If it falls, both worlds crack along the same line. Its gate is the only door the Hollow's people have left, and something comes up the cords at night to close it. Hold the gate, and climb to the Falling Sky.", "CAMPAIGN_5_.intro.ogg", "narrator"],   # CAMPAIGN[5].intro
	["The Falling Sky is not a creature. It is what the city's sky became when it stopped believing it could stay up, and when it breaks, it breaks into light. The cords hold, for now. Every door between the worlds is in your guild's hands.", "CAMPAIGN_5_.outro.ogg", "narrator"],   # CAMPAIGN[5].outro
	["The Breach closes behind Vaelith, by her own hand this time. Under her cloak is an Accord badge with the oath scratched out: she was one of them, and she left her post. Whatever the old guilds did that night, she has been undoing it. Greater Rifts are open to your guild.", "VAELITH_SPARED_OUTRO.ogg", "narrator"],   # VAELITH_SPARED_OUTRO
	["The Spire crumbles into the black water, and Nyxara with it, but not before your guild has carried out its shelves. Most of it is contracts. One book is in the Grandmaster's hand, and it says the guilds did not fall that night. They made a bargain. Beneath the Spire, something vast stirs: a rift with no bottom, lit by pillars of light. The Endless Rift is open to your guild.", "SPIRE_ARCHIVE_OUTRO.ogg", "narrator"],   # SPIRE_ARCHIVE_OUTRO
	["Nyxara is gone, and the Spire is going after her. The Accord's archive is still on its shelves: every contract, every name, every oath, three hundred years of them. Down the hill the same water is heading for Hollin, and Hollin has a mill, a mill race and forty houses. Your heroes can carry one of them out.", "SPIRE_CHOICE.ogg", "narrator"],   # SPIRE_CHOICE
	["Mother Ilse of the Last Lantern finds you after dark with a page torn from the Hollow Crown Company's books: a list of rifts, each with a date, a price, and the word opened. Captain Morrow has been opening rifts and selling the contracts to close them.\n\nShe will give it to the Crown's herald if you ask. Or the Company will pay well for a guild that keeps quiet, and its contracts would come to you.", "CHARTER_TURN.ogg", "narrator"],   # CHARTER_TURN
	["The Terms lie open on the floor of the Hall: forty-one lines, forty signed. Sign the last, and one of your heroes takes the forty-first post forever; the rifts close for good. Or burn it, and every post is released at once; the champions come home, and the Hollow comes up with them.", "ACCORD_CHOICE.ogg", "narrator"],   # ACCORD_CHOICE
	["Wen finds the last page of the Grandmaster's ledger stuck to the back cover, in a hand neither of them knows. It is a reply. \"We accept your Terms. Hold your doors, and we will not come through them. Our sky is falling. We will not ask again.\" Hesper reads it twice and puts on her coat.", "SKY_BENEATH.ogg", "narrator"],   # SKY_BENEATH
	["Every door between the worlds is in your guild's hands. Prop the city and keep the doors open, with keepers on both sides, and the Hollow's people can choose where to live. Or close them all, and let the far side fall quietly, the way it has been falling for twenty years.", "SKY_CHOICE.ogg", "narrator"],   # SKY_CHOICE
	["The Crown's herald has come to the Vale to read the new Royal Charter in the square. Wen has the Terms' first page in her satchel, with the Crown's seal above every name. The square is full. Everyone is waiting for someone to speak.", "EPILOGUE_CHOICE.ogg", "narrator"],   # EPILOGUE_CHOICE
	["Wen finds the last page of the Grandmaster's ledger stuck to the back cover, in a hand neither she nor Dobbs knows. It is a reply. \"We accept your Terms. Hold your doors, and we will not come through them. Our sky is falling. We will not ask again.\" Wen reads it twice and puts on her coat.", "HESPER_POSTED_ALT.sky_beneath.ogg", "narrator"],   # HESPER_POSTED_ALT.sky_beneath
	["Not everything that came up with the tides was hunting. Some of it was running.", "SKY_BENEATH_BY_ENDING.break.ogg", "narrator"],   # SKY_BENEATH_BY_ENDING.break
	["The posts are held in turns now. Your guild is the first that can go down, and come back.", "SKY_BENEATH_BY_ENDING.rewrite.ogg", "narrator"],   # SKY_BENEATH_BY_ENDING.rewrite
	["The Terms burn green. Forty pillars go out at once, and forty people step into the dark and start walking home. Behind them, the Hollow rises to meet the sky. It will be a hard century. It will be an honest one.", "ACCORD_ENDING.break.ogg", "narrator"],   # ACCORD_ENDING.break
	["Your guild writes one more line under the forty-first, in Hesper's hand, because hers is the only one the Terms accept: the posts are held in turns. Every guild in the Hall of Guilds sends someone down for a season, and they come back. The forty in the pillars walk home, and the Hollow stays shut behind the ones who take their place. Nobody holds it alone any more.", "ACCORD_ENDING.rewrite.ogg", "narrator"],   # ACCORD_ENDING.rewrite
	["Your guild climbs down to the forty-first post with the Terms, and Hesper writes the forty-second line there, in her own hand, because hers is the only one the Terms accept: the posts are held in turns. Then she climbs out with you. The forty in the pillars walk home, and nobody holds the Hollow alone any more.", "HESPER_POSTED_ALT.rewrite.ogg", "narrator"],   # HESPER_POSTED_ALT.rewrite
	["The city holds, barely, on new cords your guild helped tie. The rifts become doors with keepers on both sides, and the first of the Hollow's people come up through them carrying everything they own. Some of them ask for work.", "SKY_ENDING.both.ogg", "narrator"],   # SKY_ENDING.both
	["Your guild closes the doors one by one, from the glass shore to the city's gate. The far side falls quietly. The rifts heal over in a season. Some nights the new stars show low on the horizon, for a moment, and then not.", "SKY_ENDING.ours.ogg", "narrator"],   # SKY_ENDING.ours
	["The page burns green, like the Terms did. The herald reads the Charter to a quiet square and leaves your guild a letter of thanks with a pension in it. Nobody mentions the smell of smoke.", "EPILOGUE_ENDING.burn.ogg", "narrator"],   # EPILOGUE_ENDING.burn
	["Wen reads the first page in the square, slowly, so the back rows can hear. The herald leaves before she finishes. By winter the Charter is gone from every wall, and the villages choose their own guilds at a moot.", "EPILOGUE_ENDING.read.ogg", "narrator"],   # EPILOGUE_ENDING.read
	["First payday. I'm Dobbs; I keep the books. The one with the ink is Wen.", "PAYDAY_SCENES.first.0.ogg", "dobbs"],   # PAYDAY_SCENES.first.0
	["I write down what happens. Try to make it worth writing.", "PAYDAY_SCENES.first.1.ogg", "wen"],   # PAYDAY_SCENES.first.1
	["And I'm the old woman who was here before both of them. Pay your heroes and they'll stay.", "PAYDAY_SCENES.first.2.ogg", "hesper"],   # PAYDAY_SCENES.first.2
	["Someone walked out today.", "PAYDAY_SCENES.walkout.0.ogg", "dobbs"],   # PAYDAY_SCENES.walkout.0
	["Unpaid twice, or miserable. Usually both.", "PAYDAY_SCENES.walkout.1.ogg", "hesper"],   # PAYDAY_SCENES.walkout.1
	["I'll write that they left. I won't write why. That's yours to fix.", "PAYDAY_SCENES.walkout.2.ogg", "wen"],   # PAYDAY_SCENES.walkout.2
	["I've added a name to the Memorial.", "PAYDAY_SCENES.lost.0.ogg", "wen"],   # PAYDAY_SCENES.lost.0
	["Say it out loud once. It helps.", "PAYDAY_SCENES.lost.1.ogg", "hesper"],   # PAYDAY_SCENES.lost.1
	["I'll take them off the payroll. Quietly.", "PAYDAY_SCENES.lost.2.ogg", "dobbs"],   # PAYDAY_SCENES.lost.2
	["We're short. I want that written down, Wen.", "PAYDAY_SCENES.unpaid.0.ogg", "dobbs"],   # PAYDAY_SCENES.unpaid.0
	["It's written down. It was written down last week, too.", "PAYDAY_SCENES.unpaid.1.ogg", "wen"],   # PAYDAY_SCENES.unpaid.1
	["Then underline it.", "PAYDAY_SCENES.unpaid.2.ogg", "dobbs"],   # PAYDAY_SCENES.unpaid.2
	["Good feast.", "PAYDAY_SCENES.feast.0.ogg", "hesper"],   # PAYDAY_SCENES.feast.0
	["Expensive feast.", "PAYDAY_SCENES.feast.1.ogg", "dobbs"],   # PAYDAY_SCENES.feast.1
	["I'm writing 'good'.", "PAYDAY_SCENES.feast.2.ogg", "wen"],   # PAYDAY_SCENES.feast.2
	["The herald wrote our name first this week.", "PAYDAY_SCENES.we_lead.0.ogg", "wen"],   # PAYDAY_SCENES.we_lead.0
	["Did the herald pay anything?", "PAYDAY_SCENES.we_lead.1.ogg", "dobbs"],   # PAYDAY_SCENES.we_lead.1
	["No.", "PAYDAY_SCENES.we_lead.2.ogg", "wen"],   # PAYDAY_SCENES.we_lead.2
	["Then it's ink.", "PAYDAY_SCENES.we_lead.3.ogg", "dobbs"],   # PAYDAY_SCENES.we_lead.3
	["Our rivals bought new banners.", "PAYDAY_SCENES.they_lead.0.ogg", "dobbs"],   # PAYDAY_SCENES.they_lead.0
	["The Accord never had banners.", "PAYDAY_SCENES.they_lead.1.ogg", "hesper"],   # PAYDAY_SCENES.they_lead.1
	["The Accord is gone.", "PAYDAY_SCENES.they_lead.2.ogg", "dobbs"],   # PAYDAY_SCENES.they_lead.2
	["Yes. Well.", "PAYDAY_SCENES.they_lead.3.ogg", "hesper"],   # PAYDAY_SCENES.they_lead.3
	["The vault is full. I don't trust it.", "PAYDAY_SCENES.rich.0.ogg", "dobbs"],   # PAYDAY_SCENES.rich.0
	["Spend it on the heroes, then. Gold never closed a rift.", "PAYDAY_SCENES.rich.1.ogg", "hesper"],   # PAYDAY_SCENES.rich.1
	["Gold paid the ones who did.", "PAYDAY_SCENES.rich.2.ogg", "dobbs"],   # PAYDAY_SCENES.rich.2
	["These ledger pages. Hesper, did you know the Grandmaster?", "PAYDAY_SCENES.accord.0.ogg", "wen"],   # PAYDAY_SCENES.accord.0
	["Everyone knew her. Nobody knew her.", "PAYDAY_SCENES.accord.1.ogg", "hesper"],   # PAYDAY_SCENES.accord.1
	["That isn't an answer.", "PAYDAY_SCENES.accord.2.ogg", "wen"],   # PAYDAY_SCENES.accord.2
	["It's the only one she ever gave.", "PAYDAY_SCENES.accord.3.ogg", "hesper"],   # PAYDAY_SCENES.accord.3
	["Nobody hurt this week.", "PAYDAY_SCENES.quiet1.0.ogg", "hesper"],   # PAYDAY_SCENES.quiet1.0
	["That's not a story.", "PAYDAY_SCENES.quiet1.1.ogg", "wen"],   # PAYDAY_SCENES.quiet1.1
	["It's the best kind. You'll learn.", "PAYDAY_SCENES.quiet1.2.ogg", "hesper"],   # PAYDAY_SCENES.quiet1.2
	["Hesper, what were the old guilds like?", "PAYDAY_SCENES.quiet2.0.ogg", "wen"],   # PAYDAY_SCENES.quiet2.0
	["Louder. Better paid. Gone.", "PAYDAY_SCENES.quiet2.1.ogg", "hesper"],   # PAYDAY_SCENES.quiet2.1
	["Wages, upkeep, and a bill for a broken door.", "PAYDAY_SCENES.quiet3.0.ogg", "dobbs"],   # PAYDAY_SCENES.quiet3.0
	["Which door?", "PAYDAY_SCENES.quiet3.1.ogg", "wen"],   # PAYDAY_SCENES.quiet3.1
	["The one someone kicked in after the last rift. I'm not saying who.", "PAYDAY_SCENES.quiet3.2.ogg", "dobbs"],   # PAYDAY_SCENES.quiet3.2
	["I sat the Assay at sixteen. The stone barely glowed.", "PAYDAY_SCENES.quiet4.0.ogg", "hesper"],   # PAYDAY_SCENES.quiet4.0
	["What rank?", "PAYDAY_SCENES.quiet4.1.ogg", "wen"],   # PAYDAY_SCENES.quiet4.1
	["F. I'm still here. Most of the S's aren't.", "PAYDAY_SCENES.quiet4.2.ogg", "hesper"],   # PAYDAY_SCENES.quiet4.2
	["I need another word for 'rift'. I've used it four hundred times.", "PAYDAY_SCENES.quiet5.0.ogg", "wen"],   # PAYDAY_SCENES.quiet5.0
	["Use 'expense'.", "PAYDAY_SCENES.quiet5.1.ogg", "dobbs"],   # PAYDAY_SCENES.quiet5.1
	["The recruits ask what the Accord was.", "PAYDAY_SCENES.quiet6.0.ogg", "dobbs"],   # PAYDAY_SCENES.quiet6.0
	["Tell them it was a promise. Tell them we're keeping it.", "PAYDAY_SCENES.quiet6.1.ogg", "hesper"],   # PAYDAY_SCENES.quiet6.1
	["Are we?", "PAYDAY_SCENES.quiet6.2.ogg", "dobbs"],   # PAYDAY_SCENES.quiet6.2
	["Ask me next payday.", "PAYDAY_SCENES.quiet6.3.ogg", "hesper"],   # PAYDAY_SCENES.quiet6.3
	["You never said you knew them.", "PAYDAY_SCENES.past_paytable.1.ogg", "wen"],   # PAYDAY_SCENES.past_paytable.1
	["You never asked who taught you the pay table.", "PAYDAY_SCENES.past_paytable.2.ogg", "hesper"],   # PAYDAY_SCENES.past_paytable.2
	["Who pays for flowers?", "PAYDAY_SCENES.past_banner.1.ogg", "dobbs"],   # PAYDAY_SCENES.past_banner.1
	["Nobody. That's how you know they mean it.", "PAYDAY_SCENES.past_banner.2.ogg", "hesper"],   # PAYDAY_SCENES.past_banner.2
	["And kept fewer heroes.", "PAYDAY_SCENES.past_books.1.ogg", "hesper"],   # PAYDAY_SCENES.past_books.1
	["I hate it when the books agree with you.", "PAYDAY_SCENES.past_books.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_books.2
	["Already have.", "PAYDAY_SCENES.past_hero.2.ogg", "wen"],   # PAYDAY_SCENES.past_hero.2
	["We do. Once a year, on the Night of Breaking.", "PAYDAY_SCENES.past_renew.1.ogg", "hesper"],   # PAYDAY_SCENES.past_renew.1
	["I'll put it in the ledger. No charge.", "PAYDAY_SCENES.past_renew.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_renew.2
	["The tides got honest.", "PAYDAY_SCENES.past_break.1.ogg", "hesper"],   # PAYDAY_SCENES.past_break.1
	["Honest costs more.", "PAYDAY_SCENES.past_break.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_break.2
	["In my hand. I'd have liked a better pen.", "PAYDAY_SCENES.past_rewrite.1.ogg", "hesper"],   # PAYDAY_SCENES.past_rewrite.1
	["Someone goes down next season. I've budgeted for it.", "PAYDAY_SCENES.past_rewrite.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_rewrite.2
	["I found our village in the archive. A contract from ninety years ago: three rifts closed, paid in cheese.", "PAYDAY_SCENES.spire_archive.0.ogg", "wen"],   # PAYDAY_SCENES.spire_archive.0
	["At what rate?", "PAYDAY_SCENES.spire_archive.1.ogg", "dobbs"],   # PAYDAY_SCENES.spire_archive.1
	["Better than ours.", "PAYDAY_SCENES.spire_archive.2.ogg", "wen"],   # PAYDAY_SCENES.spire_archive.2
	["Hollin sent a sack of flour. And a bill for the doors.", "PAYDAY_SCENES.spire_hollin.0.ogg", "dobbs"],   # PAYDAY_SCENES.spire_hollin.0
	["Pay the bill. Keep the flour.", "PAYDAY_SCENES.spire_hollin.1.ogg", "hesper"],   # PAYDAY_SCENES.spire_hollin.1
	["I'm writing down that they sent both.", "PAYDAY_SCENES.spire_hollin.2.ogg", "wen"],   # PAYDAY_SCENES.spire_hollin.2
	["Find anything?", "PAYDAY_SCENES.past_archive.1.ogg", "hesper"],   # PAYDAY_SCENES.past_archive.1
	["Your handwriting. On most of it.", "PAYDAY_SCENES.past_archive.2.ogg", "wen"],   # PAYDAY_SCENES.past_archive.2
	["Hollin doesn't seem to mind.", "PAYDAY_SCENES.past_hollin.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_hollin.2
	["Everyone took somebody's money.", "PAYDAY_SCENES.past_quiet.1.ogg", "hesper"],   # PAYDAY_SCENES.past_quiet.1
	["They took a lot of it.", "PAYDAY_SCENES.past_quiet.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_quiet.2
	["She never did like paperwork.", "PAYDAY_SCENES.past_vaelith.1.ogg", "hesper"],   # PAYDAY_SCENES.past_vaelith.1
	["She never did like being paid, by the look of it.", "PAYDAY_SCENES.past_vaelith.2.ogg", "dobbs"],   # PAYDAY_SCENES.past_vaelith.2
	["The good ones stop. The rest get stopped.", "PAYDAY_SCENES.past_retired.1.ogg", "hesper"],   # PAYDAY_SCENES.past_retired.1
	["Which were they?", "PAYDAY_SCENES.past_retired.2.ogg", "wen"],   # PAYDAY_SCENES.past_retired.2
	["Look at their banner. It's still up.", "PAYDAY_SCENES.past_retired.3.ogg", "hesper"],   # PAYDAY_SCENES.past_retired.3
	["Vaelith asked me once if doors had two sides.", "FRAGMENTS.f_two_sides.lines.0.ogg", "hesper"],   # FRAGMENTS.f_two_sides.lines.0
	["What did you say?", "FRAGMENTS.f_two_sides.lines.1.ogg", "wen"],   # FRAGMENTS.f_two_sides.lines.1
	["That rifts don't. She looked at me like I'd failed a test I didn't know I was taking.", "FRAGMENTS.f_two_sides.lines.2.ogg", "hesper"],   # FRAGMENTS.f_two_sides.lines.2
	["Your Vaelith was a deserter, whatever the songs say. She walked off her post toward the noise, not away from it. The Chorus has never decided which was worse.", "FRAGMENTS.f_orla_deserter.text.ogg", "orla"],   # FRAGMENTS.f_orla_deserter.text
	["A note on the pay table, in ranger shorthand.", "FRAGMENTS.f_shorthand.lines.0.ogg", "wen"],   # FRAGMENTS.f_shorthand.lines.0
	["Saying?", "FRAGMENTS.f_shorthand.lines.1.ogg", "dobbs"],   # FRAGMENTS.f_shorthand.lines.1
	["\"Door holding. Four more through. Don't pay me. Feed them.\"", "FRAGMENTS.f_shorthand.lines.2.ogg", "wen"],   # FRAGMENTS.f_shorthand.lines.2
	["Feed whom?", "FRAGMENTS.f_shorthand.lines.3.ogg", "dobbs"],   # FRAGMENTS.f_shorthand.lines.3
	["Page two says \"refuse them properly\".", "FRAGMENTS.f_spelling.lines.0.ogg", "wen"],   # FRAGMENTS.f_spelling.lines.0
	["She wrote \"proper\". She never could spell. I fixed it when I wrote them out fair.", "FRAGMENTS.f_spelling.lines.1.ogg", "hesper"],   # FRAGMENTS.f_spelling.lines.1
	["When you what?", "FRAGMENTS.f_spelling.lines.2.ogg", "wen"],   # FRAGMENTS.f_spelling.lines.2
	["Hesper, your fever note is in green ink.", "FRAGMENTS.f_ink.lines.0.ogg", "wen"],   # FRAGMENTS.f_ink.lines.0
	["The Terms are in green ink.", "FRAGMENTS.f_ink.lines.1.ogg", "wen"],   # FRAGMENTS.f_ink.lines.1
	["It was the ink I had.", "FRAGMENTS.f_ink.lines.2.ogg", "hesper"],   # FRAGMENTS.f_ink.lines.2
	["My regards to Hesper. I still have the blanket she lent me on the night she was meant to be in bed with a fever. She was never sick a day in her life.", "FRAGMENTS.f_ilse_never_sick.text.ogg", "ilse"],   # FRAGMENTS.f_ilse_never_sick.text
	["Last week he smelled of fish.", "FRAGMENTS.f_pip_theft.lines.1.ogg", "wen"],   # FRAGMENTS.f_pip_theft.lines.1
	["My cousin is Warden of the Crown's Rifts, and the Vale is safe in his hands. He did lose a key once, to a girl no taller than a sword. We don't mention it.", "FRAGMENTS.f_aldric_cousin.text.ogg", "aldric"],   # FRAGMENTS.f_aldric_cousin.text
	["Ezra's lantern was on the step again this morning.", "FRAGMENTS.f_lantern_full.lines.0.ogg", "dobbs"],   # FRAGMENTS.f_lantern_full.lines.0
	["Empty, like last time?", "FRAGMENTS.f_lantern_full.lines.1.ogg", "wen"],   # FRAGMENTS.f_lantern_full.lines.1
	["Full. Hundreds of little lights. Some of them are saying names. Not ours.", "FRAGMENTS.f_lantern_full.lines.2.ogg", "dobbs"],   # FRAGMENTS.f_lantern_full.lines.2
	["The smugglers' crates came in. I was promised Essence.", "FRAGMENTS.f_lamp_oil.lines.0.ogg", "dobbs"],   # FRAGMENTS.f_lamp_oil.lines.0
	["And?", "FRAGMENTS.f_lamp_oil.lines.1.ogg", "wen"],   # FRAGMENTS.f_lamp_oil.lines.1
	["Lamp oil. Nine casks. Mother Ilse's compliments, and \"keep the Lamp lit\".", "FRAGMENTS.f_lamp_oil.lines.2.ogg", "dobbs"],   # FRAGMENTS.f_lamp_oil.lines.2
	["Day three: \"A voice offered terms.\"", "FRAGMENTS.f_side_by_side.lines.0.ogg", "wen"],   # FRAGMENTS.f_side_by_side.lines.0
	["The last page: \"We accept your Terms.\"", "FRAGMENTS.f_side_by_side.lines.1.ogg", "wen"],   # FRAGMENTS.f_side_by_side.lines.1
	["Read them both again. Slower.", "FRAGMENTS.f_side_by_side.lines.2.ogg", "dobbs"],   # FRAGMENTS.f_side_by_side.lines.2
	["I have. Nobody wants the last biscuit.", "FRAGMENTS.f_side_by_side.lines.3.ogg", "wen"],   # FRAGMENTS.f_side_by_side.lines.3
	["The new recruit asked when \"our keepers\" get paid.", "FRAGMENTS.f_our_keepers.lines.0.ogg", "dobbs"],   # FRAGMENTS.f_our_keepers.lines.0
	["Which keepers?", "FRAGMENTS.f_our_keepers.lines.1.ogg", "wen"],   # FRAGMENTS.f_our_keepers.lines.1
	["The ones holding their side of the doors. She says they take turns, like ours.", "FRAGMENTS.f_our_keepers.lines.2.ogg", "dobbs"],   # FRAGMENTS.f_our_keepers.lines.2
	["The Warden's ring. I've seen this seal before.", "FRAGMENTS.f_ring_match.lines.0.ogg", "wen"],   # FRAGMENTS.f_ring_match.lines.0
	["Where?", "FRAGMENTS.f_ring_match.lines.1.ogg", "dobbs"],   # FRAGMENTS.f_ring_match.lines.1
	["On the Terms. Above every signature.", "FRAGMENTS.f_ring_match.lines.2.ogg", "wen"],   # FRAGMENTS.f_ring_match.lines.2
	["My cousin has been recalled to the capital. Something about a seal, a ring, and questions he would rather not answer. The Lance is, of course, above such things.", "FRAGMENTS.f_recalled.text.ogg", "aldric"],   # FRAGMENTS.f_recalled.text
	["Keep your walls up. The Hollow came for the Vale once, the night the old guilds fell, and it will come again.", "RIVAL_CLAIM_LETTERS.orla_attack.ogg", "orla"],   # RIVAL_CLAIM_LETTERS.orla_attack
	["Remember who paid for the posts. The Crown kept the Vale alive when the guilds could not. The Chorus remembers.", "RIVAL_CLAIM_LETTERS.orla_crown.ogg", "orla"],   # RIVAL_CLAIM_LETTERS.orla_crown
	["Whatever they tell you about the old guilds, remember that they were betrayed by the one they trusted most. I knew her.", "RIVAL_CLAIM_LETTERS.ilse_betrayed.ogg", "ilse"],   # RIVAL_CLAIM_LETTERS.ilse_betrayed
	["Watch the Hollow Crown Company. Count the rifts that open on their roads, and the contracts that follow.", "RIVAL_CLAIM_LETTERS.ilse_profit.ogg", "ilse"],   # RIVAL_CLAIM_LETTERS.ilse_profit
	["Morrow hasn't the coin to do what he does. Someone pays him. I'm still finding out who.", "RIVAL_CLAIM_LETTERS.ilse_paid.ogg", "ilse"],   # RIVAL_CLAIM_LETTERS.ilse_paid
	["There's no Hollow, friend. There are doors, and whoever holds the keys. The rest is sermons.", "RIVAL_CLAIM_LETTERS.morrow_no_hollow.ogg", "morrow"],   # RIVAL_CLAIM_LETTERS.morrow_no_hollow
	["And before you ask: I work for nobody but myself. Ask anyone.", "RIVAL_CLAIM_LETTERS.morrow_himself.ogg", "morrow"],   # RIVAL_CLAIM_LETTERS.morrow_himself
	["Every guild sells rifts. Mine just keeps receipts.", "RIVAL_CLAIM_LETTERS.morrow_receipts.ogg", "morrow"],   # RIVAL_CLAIM_LETTERS.morrow_receipts
	["My grandfather said the old guilds sold too much Essence to too many buyers, and the Hollow came to collect. Grandfather was rarely wrong.", "RIVAL_CLAIM_LETTERS.aldric_sold.ogg", "aldric"],   # RIVAL_CLAIM_LETTERS.aldric_sold
	["And no, there is no key that opens rifts. That's a story for children and smugglers.", "RIVAL_CLAIM_LETTERS.aldric_myth.ogg", "aldric"],   # RIVAL_CLAIM_LETTERS.aldric_myth
	["The Hollow is a mouth. You feed it or you burn it. My wolves know which.", "RIVAL_CLAIM_LETTERS.kael_hunger.ogg", "kael"],   # RIVAL_CLAIM_LETTERS.kael_hunger
	["Say what you like about the Ashen Crown. For ten years nobody in the ash starved. Count that.", "RIVAL_CLAIM_LETTERS.kael_crown.ogg", "kael"],   # RIVAL_CLAIM_LETTERS.kael_crown
	["And my wolves owe nobody. Not the Crown, not the old guilds, not you.", "RIVAL_CLAIM_LETTERS.kael_owe.ogg", "kael"],   # RIVAL_CLAIM_LETTERS.kael_owe
	["That contract is on the board and we can do it. So can you, maybe. First to sign it keeps it.", "RIVAL_VOICE.orla.snatch.ogg", "orla"],   # RIVAL_VOICE.orla.snatch
	["We need that contract more than you do. I'm not proud of saying so. I'm saying it anyway.", "RIVAL_VOICE.kael.snatch.ogg", "kael"],   # RIVAL_VOICE.kael.snatch
	["The Lance will be taking that contract. Do not trouble yourselves.", "RIVAL_VOICE.aldric.snatch.ogg", "aldric"],   # RIVAL_VOICE.aldric.snatch
	["The Charter will hang in the Lance's hall. I have already chosen the frame.", "RIVAL_VOICE.aldric.taunts.0.ogg", "aldric"],   # RIVAL_VOICE.aldric.taunts.0
	["The Wolves will try for this one tomorrow. Take it first and I'll know you can be trusted with better news. Let it go and I'll take it, and I'll know that too.", "RIVAL_VOICE.ilse.snatch.ogg", "ilse"],   # RIVAL_VOICE.ilse.snatch
	["We'll take this one off your hands. Plenty of work for everyone; there always seems to be, near us.", "RIVAL_VOICE.morrow.snatch.ogg", "morrow"],   # RIVAL_VOICE.morrow.snatch
	["There was a girl on the other side of my door. I told her to wait, that I'd come back for her. I'd like to know if she did.", "CHAMPION_MEMORY.brannoch.ogg", "brannoch"],   # CHAMPION_MEMORY.brannoch
]
